# Activation clustering defense

In this notebook we will evaluate the effect of filtering using activation clustering (Chen et al. https://arxiv.org/pdf/1811.03728.pdf) when applied to subpopulation attacks on the sentiment classification task.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import gc
import sys

In [3]:
os.chdir('../../')

In [4]:
import tqdm
import torch
import numpy as np
import pandas as pd

from transformers import AdamW
from sklearn.cluster import KMeans
from sklearn.decomposition import FastICA
from sklearn.metrics import silhouette_score
from torch.utils.data import TensorDataset, DataLoader
from art.defences.detector.poison import ActivationDefence
from art.estimators.classification import PyTorchClassifier

/home/giorgio/.pyenv/versions/3.6.8/envs/subpop/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [5]:
from attack_nlp import init_cluster_attack

from subclass_avail import common
from subclass_avail.target_nlp import bert_utils

## Constants

In [6]:
results_dir = 'results/bert'
fname = 'eval-stats_clus{}_pois{}_{}.npy'

n_clus = 100
seed = 42

pois_rate = '2.0'
m_type = 'FT'
frozen = False

In [7]:
# Set the random seed to the same used during the attack
device = bert_utils.get_device()
bert_utils.set_seed(device=device, seed=seed)

Available device:  cuda


## Attack results


Let's first look at the subpopulation with highest target damage.
We will use that subpopulation as target for our defense.

In [8]:
# Accumulate all results in a single DataFrame
res_df = pd.DataFrame(columns=['type', 'p_rate', 'index', 't_dmg', 'p_acc', 'base_def', 'coll_dmg', 'csize', 'exp'])


exp_name = fname.format(n_clus, pois_rate, m_type)
res_arr = np.load(os.path.join(common.results_dir_bert, exp_name)).item()

for clus_id, results in res_arr.items():
    if len(results['train_clus_size']) > 1:
        train_clus_size = len(results['train_clus_size'])
    else:
        train_clus_size = results['train_clus_size'][0]

    to_add = {
        'type': m_type,
        'p_rate': pois_rate,
        'index': clus_id,
        't_dmg': results['base_def'] - results['pois'],
        'p_acc': results['pois'],
        'base_def': results['base_def'],
        'coll_dmg': results['collateral_dmg'],
        'csize': train_clus_size,
        'exp': exp_name
    }

    res_df = res_df.append(to_add, ignore_index=True)
    
# Sorting by target damage

exp_name = fname.format(n_clus, pois_rate, m_type)

sub_df = res_df[res_df['exp'] == exp_name]
sub_df = sub_df.sort_values(by='t_dmg')

top5_df = sub_df.tail(5)
top10_df = sub_df.tail(10)

print('Best target damage:')
print(sub_df[-1:])
victim_pop = sub_df[-1:]['index'].item()
print()

Best target damage:
   type p_rate index     t_dmg     p_acc  base_def  coll_dmg csize  \
14   FT    2.0    24  0.505814  0.482558  0.988372  0.003746    91   

                                  exp  
14  eval-stats_clus100_pois2.0_FT.npy  



## Attack data

In [9]:
cl_ind = victim_pop
pth = os.path.join(common.storage_dir, 'imdb_bert_{}_pop_{}'.format('LL' if frozen else 'FT', cl_ind))

pois_x = np.load(os.path.join(pth, 'pois_x_{}.npy'.format(cl_ind)), allow_pickle=True)
pois_x_att = np.load(os.path.join(pth, 'pois_x_att_{}.npy'.format(cl_ind)), allow_pickle=True)
pois_y = np.load(os.path.join(pth, 'pois_y_{}.npy'.format(cl_ind)), allow_pickle=True)

trn_x = np.load(os.path.join(pth, 'trn_x_{}.npy'.format(cl_ind)), allow_pickle=True)
trn_x_att = np.load(os.path.join(pth, 'trn_x_att_{}.npy'.format(cl_ind)), allow_pickle=True)
trn_y = np.load(os.path.join(pth, 'trn_y_{}.npy'.format(cl_ind)), allow_pickle=True)

x_t = np.load(os.path.join(pth, 'x_t_{}.npy'.format(cl_ind)), allow_pickle=True)
x_t_att = np.load(os.path.join(pth, 'x_t_att_{}.npy'.format(cl_ind)), allow_pickle=True)
y_t = np.load(os.path.join(pth, 'y_t_{}.npy'.format(cl_ind)), allow_pickle=True)

xt_p = np.load(os.path.join(pth, 'xt_p_{}.npy'.format(cl_ind)), allow_pickle=True)
xt_p_att = np.load(os.path.join(pth, 'xt_p_att_{}.npy'.format(cl_ind)), allow_pickle=True)
yt_p = np.load(os.path.join(pth, 'yt_p_{}.npy'.format(cl_ind)), allow_pickle=True)

x_coll = np.load(os.path.join(pth, 'x_coll_{}.npy'.format(cl_ind)), allow_pickle=True)
x_coll_att = np.load(os.path.join(pth, 'x_coll_att_{}.npy'.format(cl_ind)), allow_pickle=True)
y_coll = np.load(os.path.join(pth, 'y_coll_{}.npy'.format(cl_ind)), allow_pickle=True)


In [10]:
poison_idx = np.zeros_like(trn_y)
poison_idx[-pois_y.shape[0]:] = 1

In [11]:
pois_idx0 = poison_idx[trn_y == 0]
pois_idx1 = poison_idx[trn_y == 1]

In [12]:
sum(pois_idx0)

150

In [13]:
num_poisons = pois_y.shape[0]
print(num_poisons)

150


## Load the attacked model

We can now load the attacked model for the selected subpopulation 

In [14]:
print('Loading victim model for subpopulation {}'.format(victim_pop))

victim_model_path = os.path.join(
    common.saved_models_dir,
    'victim_bert_{}'.format(victim_pop)
) + '.ckpt'
victim_model = bert_utils.load_bert(model_file=victim_model_path)

Loading victim model for subpopulation 24
Loading model: /media/storage/projects/research/advml/subclass/saved_models/victim_bert_24.ckpt


In [15]:
tst_ds = TensorDataset(torch.from_numpy(x_t), torch.from_numpy(x_t_att), torch.from_numpy(x_t))
tst_dl = DataLoader(tst_ds, shuffle=False, batch_size=8)

tst_p_ds = TensorDataset(torch.from_numpy(xt_p), torch.from_numpy(xt_p_att), torch.from_numpy(yt_p))
tst_p_dl = DataLoader(tst_p_ds, shuffle=False, batch_size=8)

In [16]:
tst_pred = bert_utils.predict_bert(victim_model, device, tst_dl)
_ = bert_utils.eval_classification(tst_pred, y_t)

tst_p_pred = bert_utils.predict_bert(victim_model, device, tst_p_dl)
_ = bert_utils.eval_classification(tst_p_pred, yt_p)

  9%|▉         | 2/22 [00:00<00:01, 13.17it/s]

              precision    recall  f1-score   support

           0   0.905357  0.904560  0.904958     12500
           1   0.904644  0.905440  0.905042     12500

    accuracy                       0.905000     25000
   macro avg   0.905000  0.905000  0.905000     25000
weighted avg   0.905000  0.905000  0.905000     25000

[[11307  1193]
 [ 1182 11318]]


100%|██████████| 22/22 [00:01<00:00, 13.32it/s]

              precision    recall  f1-score   support

           0   0.011236  0.500000  0.021978         2
           1   0.987952  0.482353  0.648221       170

    accuracy                       0.482558       172
   macro avg   0.499594  0.491176  0.335100       172
weighted avg   0.976595  0.482558  0.640939       172

[[ 1  1]
 [88 82]]


In [17]:
del tst_pred, tst_p_pred

## Defense

In [18]:
t_x = torch.from_numpy(trn_x)
t_a = torch.from_numpy(trn_x_att)
t_y = torch.from_numpy(trn_y)
train_ds = TensorDataset(t_x, t_a, t_y)
train_dl = DataLoader(train_ds, shuffle=True, batch_size=2)

In [19]:
repres_trn = bert_utils.get_representations(
    model_name='victim_bert_{}_pois{}_pop{}'.format('LL' if frozen else 'FT', pois_rate, cl_ind),
    model=victim_model,
    data_loader=train_dl,
    f_name='trn_x',
    b_size=2
)

Available device:  cuda
Representation size:(12650, 256, 768)


In [20]:
classes = [0, 1]
nb_dims = 15

In [21]:
remove_lists = []

for cls in classes:
    print('CLASS', cls)
    
    repres = repres_trn[trn_y == cls]
    repres = repres.reshape(repres.shape[0], -1)
    
    proj = FastICA(n_components=nb_dims, max_iter=1000, tol=0.005)
    repres_proj = proj.fit_transform(repres)
    
    kmeans = KMeans(n_clusters=2)
    kmeans.fit(repres_proj)
    
    print('Clustering for class:', cls)
    labels = kmeans.labels_
    
    clus_0 = labels == 0
    clus_1 = labels == 1
    print('Sizes of clusters: {} - {}'.format(sum(clus_0), sum(clus_1)))
    silh = silhouette_score(repres_proj, labels, metric='euclidean')
    print('Silhouette score', silh)

    # make bitmap with samples to remove
    to_remove = np.zeros(shape=repres.shape[0])
    
#     if silh >= 0.1:
    to_remove_idx = np.argmin([sum(clus_0), sum(clus_1)])
    print('Removing cluster: ', to_remove_idx)
    to_remove = clus_0 if to_remove_idx == 0 else clus_1
    
    print(to_remove.shape)
    print(sum(to_remove))
    remove_lists.append(to_remove)
    
    del kmeans, repres_proj, labels, silh

CLASS 0
Clustering for class: 0
Sizes of clusters: 3157 - 3243
Silhouette score 0.07836318349966272
Removing cluster:  0
(6400,)
3157
CLASS 1
Clustering for class: 1
Sizes of clusters: 3184 - 3066
Silhouette score 0.07450561119752815
Removing cluster:  1
(6250,)
3066


In [22]:
found = 0
rl0 = remove_lists[0]
rl1 = remove_lists[1]

for i in range(len(rl0)):
    if rl0[i] == 1 and pois_idx0[i] == 1:
        found +=1

for i in range(len(rl1)):
    if rl1[i] == 1 and pois_idx1[i] == 1:
        found +=1

print(found)

67


In [23]:
def_trn_x0 = np.copy(trn_x[trn_y == 0])
def_trn_a0 = np.copy(trn_x_att[trn_y == 0])
def_trn_y0 = np.copy(trn_y[trn_y == 0])
def_trn_x1 = np.copy(trn_x[trn_y == 1])
def_trn_a1 = np.copy(trn_x_att[trn_y == 1])
def_trn_y1 = np.copy(trn_y[trn_y == 1])
print(def_trn_x0.shape, def_trn_y0.shape, def_trn_a0.shape, def_trn_x1.shape, def_trn_a1.shape, def_trn_y1.shape)

(6400, 256) (6400,) (6400, 256) (6250, 256) (6250, 256) (6250,)


In [24]:
def_trn_x0 = def_trn_x0[~remove_lists[0].astype(bool)]
def_trn_a0 = def_trn_a0[~remove_lists[0].astype(bool)]
def_trn_y0 = def_trn_y0[~remove_lists[0].astype(bool)]
print(def_trn_x0.shape, def_trn_a0.shape, def_trn_y0.shape)

def_trn_x1 = def_trn_x1[~remove_lists[1].astype(bool)]
def_trn_a1 = def_trn_a1[~remove_lists[1].astype(bool)]
def_trn_y1 = def_trn_y1[~remove_lists[1].astype(bool)]
print(def_trn_x1.shape, def_trn_a1.shape, def_trn_y1.shape)

def_trn_x = np.concatenate([def_trn_x0, def_trn_x1])
def_trn_a = np.concatenate([def_trn_a0, def_trn_a1])
def_trn_y = np.concatenate([def_trn_y0, def_trn_y1])
print(def_trn_x.shape, def_trn_a.shape, def_trn_y.shape)

shuffle_idx = np.random.choice(def_trn_x.shape[0], def_trn_x.shape[0], replace=False)
print(shuffle_idx.shape)

def_trn_x = def_trn_x[shuffle_idx]
def_trn_a = def_trn_a[shuffle_idx]
def_trn_y = def_trn_y[shuffle_idx]
print(def_trn_x.shape, def_trn_a.shape, def_trn_y.shape)

(3243, 256) (3243, 256) (3243,)
(3184, 256) (3184, 256) (3184,)
(6427, 256) (6427, 256) (6427,)
(6427,)
(6427, 256) (6427, 256) (6427,)


In [25]:
del victim_model
gc.collect()
torch.cuda.empty_cache()

In [26]:
def_model = bert_utils.wrap_train(
    trn_x=def_trn_x,
    trn_y=def_trn_y,
    trn_x_att=def_trn_a,
    frozen=frozen
)

Available device:  cuda


  0%|          | 0/804 [00:00<?, ?it/s]

Epoch 0 of 4


100%|██████████| 804/804 [03:10<00:00,  4.21it/s]


Train loss at epoch 0: 0.37547311685349216


  0%|          | 0/804 [00:00<?, ?it/s]

Training accuracy - epoch 0: 0.9341832504145937
Epoch 1 of 4


100%|██████████| 804/804 [03:13<00:00,  4.15it/s]


Train loss at epoch 1: 0.20935666743221124


  0%|          | 0/804 [00:00<?, ?it/s]

Training accuracy - epoch 1: 0.9631529850746269
Epoch 2 of 4


100%|██████████| 804/804 [03:13<00:00,  4.15it/s]


Train loss at epoch 2: 0.12466052263993677


  0%|          | 0/804 [00:00<?, ?it/s]

Training accuracy - epoch 2: 0.9841417910447762
Epoch 3 of 4


100%|██████████| 804/804 [03:14<00:00,  4.14it/s]


Train loss at epoch 3: 0.07599472524644575
Training accuracy - epoch 3: 0.986318407960199


In [27]:
tst_pred = bert_utils.predict_bert(def_model, device, tst_dl)
_ = bert_utils.eval_classification(tst_pred, y_t)

tst_p_pred = bert_utils.predict_bert(def_model, device, tst_p_dl)
_ = bert_utils.eval_classification(tst_p_pred, yt_p)

  9%|▉         | 2/22 [00:00<00:01, 13.15it/s]

              precision    recall  f1-score   support

           0   0.904716  0.899360  0.902030     12500
           1   0.899952  0.905280  0.902608     12500

    accuracy                       0.902320     25000
   macro avg   0.902334  0.902320  0.902319     25000
weighted avg   0.902334  0.902320  0.902319     25000

[[11242  1258]
 [ 1184 11316]]


100%|██████████| 22/22 [00:01<00:00, 13.28it/s]

              precision    recall  f1-score   support

           0   0.000000  0.000000  0.000000         2
           1   0.978495  0.535294  0.692015       170

    accuracy                       0.529070       172
   macro avg   0.489247  0.267647  0.346008       172
weighted avg   0.967117  0.529070  0.683969       172

[[ 0  2]
 [79 91]]


## Base

In [28]:
del def_model
gc.collect()
torch.cuda.empty_cache()

In [29]:
model_name_def = 'imdb_bert_{}_DEF'.format('LL' if frozen else 'FT')
model_def = bert_utils.load_bert(model_file=model_name_def + '.ckpt')

Loading model: imdb_bert_FT_DEF.ckpt


In [30]:
tst_pred = bert_utils.predict_bert(model_def, device, tst_dl)
_ = bert_utils.eval_classification(tst_pred, y_t)

tst_p_pred = bert_utils.predict_bert(model_def, device, tst_p_dl)
_ = bert_utils.eval_classification(tst_p_pred, yt_p)

  9%|▉         | 2/22 [00:00<00:01, 13.14it/s]

              precision    recall  f1-score   support

           0   0.922579  0.899920  0.911108     12500
           1   0.902319  0.924480  0.913265     12500

    accuracy                       0.912200     25000
   macro avg   0.912449  0.912200  0.912187     25000
weighted avg   0.912449  0.912200  0.912187     25000

[[11249  1251]
 [  944 11556]]


100%|██████████| 22/22 [00:01<00:00, 13.28it/s]

              precision    recall  f1-score   support

           0   0.000000  0.000000  0.000000         2
           1   0.988372  1.000000  0.994152       170

    accuracy                       0.988372       172
   macro avg   0.494186  0.500000  0.497076       172
weighted avg   0.976879  0.988372  0.982592       172

[[  0   2]
 [  0 170]]



/home/giorgio/.pyenv/versions/3.6.8/envs/subpop/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
